version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tools-sharing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: toolssharing
      MYSQL_USER: toolsuser
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    profiles:
      - infrastructure
      - full

  redis:
    image: redis:7-alpine
    container_name: tools-sharing-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - ENABLE_REDIS_PASSWORD=${ENABLE_REDIS_PASSWORD:-true}
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: >
      sh -c "
      if [ \"$$ENABLE_REDIS_PASSWORD\" = \"true\" ] && [ -n \"$$REDIS_PASSWORD\" ]; then
        echo 'Starting Redis with password authentication...';
        redis-server --requirepass \"$$REDIS_PASSWORD\";
      else
        echo 'Starting Redis without password authentication...';
        redis-server;
      fi
      "
    profiles:
      - infrastructure
      - full

  minio:
    image: minio/minio:latest
    container_name: tools-sharing-minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    profiles:
      - infrastructure
      - full

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tools-sharing-api
    ports:
      - "5002:5002"
      - "5003:5003"
    depends_on:
      - mysql
      - redis
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5003;http://+:5002
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=toolssharing;uid=toolsuser;pwd=${MYSQL_USER_PASSWORD}
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD}
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=${MINIO_ROOT_USER}
      - MinIO__SecretKey=${MINIO_ROOT_PASSWORD}
    restart: unless-stopped
    profiles:
      - api
      - full

volumes:
  mysql_data:
  minio_data: